export const levels=['A1','A2','B1','B2'];
export const vocabulary=[
['morning','утро','A1','I read in the morning.','the early part of the day'],['friend','друг','A1','My friend lives near me.','a person you like and know well'],['happy','счастливый','A1','I am happy today.','feeling good'],['learn','учить, изучать','A1','I learn English every day.','to get new knowledge'],['home','дом','A1','I walk home after school.','the place where you live'],['water','вода','A1','I drink water.','a clear liquid we drink'],['book','книга','A1','This book is interesting.','pages with words to read'],['small','маленький','A1','We have a small garden.','not big'],
['journey','путешествие','A2','Our journey starts today.','a trip from one place to another'],['enjoy','наслаждаться','A2','I enjoy reading stories.','to like doing something'],['quiet','тихий','A2','This is a quiet place.','with little noise'],['choose','выбирать','A2','Choose a book you like.','to decide which thing you want'],['improve','улучшать','A2','Practice helps me improve.','to make something better'],['arrive','прибывать','A2','We arrive at six.','to get to a place'],['habit','привычка','A2','Reading is a good habit.','something you do often'],['together','вместе','A2','We study together.','with another person'],
['achieve','достигать','B1','You can achieve your goal.','to succeed in doing something'],['experience','опыт','B1','It was a useful experience.','something that happens to you or knowledge from doing things'],['confident','уверенный','B1','I feel confident when I speak.','sure that you can do something'],['instead','вместо этого','B1','I walked instead.','in place of something else'],['notice','замечать','B1','I notice new words in books.','to see or become aware of something'],['opportunity','возможность','B1','This is an opportunity to learn.','a chance to do something'],['support','поддерживать','B1','My friends support me.','to help someone'],['suggest','предлагать','B1','I suggest a short break.','to give an idea'],
['approach','подход','B2','Try a different approach.','a way of doing something'],['benefit','польза','B2','One benefit is better health.','a good result or advantage'],['challenge','сложная задача','B2','Learning a language is a challenge.','something difficult that tests your skills'],['consider','обдумывать','B2','Consider all your options.','to think carefully about something'],['develop','развивать','B2','We develop new skills.','to grow or make something grow'],['effort','усилие','B2','Progress takes effort.','energy used to do something'],['available','доступный','B2','The course is available online.','ready to be used'],['reliable','надёжный','B2','She is a reliable friend.','someone or something you can trust']
].map(([word,translation,level,example,definition])=>({word,translation,level,example,definition}));
export const lessons=[
{level:'A1',title:'To be: am, is, are',desc:'Как сказать «я студент» и «она дома».',rule:'В английском предложению обычно нужен глагол. Для состояния, возраста и профессии используй to be: I am; he / she / it is; you / we / they are.',formula:'I am · She is · They are',examples:['I am a student. — Я студент.','She is at home. — Она дома.','Are you happy? — Ты счастлив?'],tip:'Не говори I student. Правильно: I am a student.',q:'She ___ my friend.',answers:['is','am','are'],answer:'is'},
{level:'A1',title:'Present Simple',desc:'Привычки и действия, которые повторяются.',rule:'Используй для привычек и фактов. После he, she, it добавь -s или -es к глаголу. В вопросе используй do / does, в отрицании — don’t / doesn’t. После does глагол без -s.',formula:'I work → She works',examples:['I read every day. — Я читаю каждый день.','He doesn’t work on Sunday. — Он не работает в воскресенье.'],tip:'Does she like tea? Не Does she likes tea?',q:'He ___ English every day.',answers:['study','studies','studying'],answer:'studies'},
{level:'A1',title:'A / an / the',desc:'Артикли простыми словами.',rule:'A / an — один предмет, о котором говорим впервые или не конкретно. An ставится перед гласным звуком. The — конкретный предмет, понятный собеседнику. A / an используются только с исчисляемым существительным в единственном числе.',formula:'a book · an apple · the book on my desk',examples:['I have a book. The book is good. — У меня есть книга. Эта книга хорошая.','She is a teacher. — Она учитель.'],tip:'Смотри на звук: an hour, но a university.',q:'I eat ___ apple every day.',answers:['a','an','—'],answer:'an'},
{level:'A2',title:'Past Simple',desc:'Рассказываем о том, что уже произошло.',rule:'Для завершённого действия в прошлом. К правильному глаголу добавь -ed. У неправильных глаголов своя форма: go → went. После did / didn’t используй начальную форму.',formula:'visited · went · did not go',examples:['I visited my friend yesterday. — Вчера я навестил друга.','Did you go home? — Ты пошёл домой?'],tip:'I didn’t go, а не I didn’t went.',q:'Yesterday we ___ to the park.',answers:['go','went','going'],answer:'went'},
{level:'A2',title:'Present Continuous',desc:'Что происходит прямо сейчас.',rule:'Используй am / is / are + глагол с -ing для действия в процессе сейчас. Для привычек нужен Present Simple.',formula:'am / is / are + verb-ing',examples:['I am reading now. — Я сейчас читаю.','They are not sleeping. — Они не спят.'],tip:'Не забывай to be: She is working.',q:'They ___ studying now.',answers:['are','is','am'],answer:'are'},
{level:'A2',title:'Comparatives',desc:'Как сравнить два предмета.',rule:'К коротким прилагательным обычно добавляем -er: small → smaller. С длинными используем more: more interesting. После сравнения часто идёт than — «чем».',formula:'smaller than · more useful than',examples:['This room is smaller than mine. — Эта комната меньше моей.','This book is more interesting. — Эта книга интереснее.'],tip:'Исключения: good → better; bad → worse.',q:'This book is ___ than that one.',answers:['good','better','best'],answer:'better'},
{level:'B1',title:'Present Perfect',desc:'Прошлое, которое связано с настоящим.',rule:'Have / has + третья форма глагола. Говорим об опыте или результате сейчас, не называя законченное время в прошлом. С yesterday обычно нужен Past Simple.',formula:'have / has + past participle',examples:['I have lost my keys. — Я потерял ключи (сейчас их нет).','Have you ever been to London? — Ты когда-нибудь был в Лондоне?'],tip:'She has gone, но They have gone.',q:'She ___ finished her work.',answers:['have','has','is'],answer:'has'},
{level:'B1',title:'First Conditional',desc:'Реальная возможность в будущем.',rule:'После if используй Present Simple. Во второй части — will + начальная форма. Это условие, которое вполне может исполниться.',formula:'If + Present Simple, will + verb',examples:['If it rains, I will stay home. — Если пойдёт дождь, я останусь дома.'],tip:'Не ставь will сразу после if в таком условии.',q:'If I have time, I ___ help you.',answers:['will','would','did'],answer:'will'},
{level:'B1',title:'Passive Voice',desc:'Когда важнее действие, чем исполнитель.',rule:'Используй be в нужном времени + третью форму глагола. Исполнителя можно добавить после by.',formula:'be + past participle',examples:['English is spoken here. — Здесь говорят по-английски.','The book was written in 2000. — Книга была написана в 2000 году.'],tip:'Время меняет be: is made / was made.',q:'The window ___ broken yesterday.',answers:['is','was','were'],answer:'was'},
{level:'B2',title:'Second Conditional',desc:'Представляем нереальную ситуацию.',rule:'If + Past Simple, затем would + глагол. Это воображаемая или маловероятная ситуация сейчас или в будущем, а не история о прошлом.',formula:'If + Past Simple, would + verb',examples:['If I had more time, I would travel. — Если бы у меня было больше времени, я бы путешествовал.'],tip:'В советах: If I were you… — На твоём месте…',q:'If I knew the answer, I ___ tell you.',answers:['will','would','can'],answer:'would'},
{level:'B2',title:'Past Perfect',desc:'Действие, которое случилось ещё раньше.',rule:'Had + третья форма показывает действие, которое произошло до другого момента в прошлом.',formula:'had + past participle',examples:['When I arrived, the lesson had started. — Когда я пришёл, урок уже начался.'],tip:'Had одинаково для I, she, we и остальных.',q:'By the time I arrived, he ___ left.',answers:['has','had','have'],answer:'had'},
{level:'B2',title:'Reported Speech',desc:'Передаём чужие слова.',rule:'После said / told в прошедшем времени часто сдвигаем время назад: am → was, have → had, will → would. Также меняем местоимения по смыслу. Если факт всё ещё верен, сдвиг времени не всегда обязателен.',formula:'“I am tired.” → She said she was tired.',examples:['He said he would call me. — Он сказал, что позвонит мне.'],tip:'He told me, но He said to me.',q:'“I will help.” → She said she ___ help.',answers:['will','would','is'],answer:'would'}
];
export const stories=[
{level:'A1',title:'A little morning ritual',ru:'Маленький утренний ритуал',text:'Every morning, Anna reads a book at home. She drinks water and looks at her small garden. Her friend comes at ten. They learn English together. Anna is happy.',translation:'Каждое утро Анна читает книгу дома. Она пьёт воду и смотрит на свой маленький сад. Её друг приходит в десять. Они вместе учат английский. Анна счастлива.',words:['morning','book','home','small','friend','learn','happy'],q:'What does Anna read?',answers:['A book','A letter','A menu'],answer:'A book'},
{level:'A2',title:'A different way home',ru:'Другой путь домой',text:'Mia wanted to improve her English. She decided to choose a new habit: listen to a short story on her journey home. She found a quiet place on the bus. Now she and her brother enjoy learning together. They arrive home with something new to talk about.',translation:'Мия хотела улучшить свой английский. Она решила выбрать новую привычку: слушать короткую историю по дороге домой. Она нашла тихое место в автобусе. Теперь они с братом с удовольствием учатся вместе. Они приезжают домой с новой темой для разговора.',words:['improve','choose','habit','journey','quiet','enjoy','together','arrive'],q:'When does Mia listen to a story?',answers:['On her journey home','Before breakfast','At midnight'],answer:'On her journey home'},
{level:'B1',title:'One small conversation',ru:'Один маленький разговор',text:'Dan did not feel confident speaking English. His teacher suggested a simple idea: talk to one new person each week. At a café, he met a visitor and offered to help. It was a good experience. Dan noticed that mistakes were not a problem. Every conversation was an opportunity to learn and achieve his goal.',translation:'Дан не чувствовал уверенности, когда говорил по-английски. Учитель предложил простую идею: каждую неделю разговаривать с одним новым человеком. В кафе он встретил приезжего и предложил помощь. Это был хороший опыт. Дан заметил, что ошибки не были проблемой. Каждый разговор был возможностью учиться и достигать своей цели.',words:['confident','experience','opportunity','achieve'],q:'What did the teacher suggest?',answers:['Talk to a new person each week','Stop speaking','Only read books'],answer:'Talk to a new person each week'},
{level:'B2',title:'Progress, not perfection',ru:'Прогресс, а не совершенство',text:'Eva used to study for hours and then give up for weeks. She decided to consider a different approach. Instead of long sessions, she made a small effort every day. Free lessons were available online, and a reliable friend helped her practise. The challenge was to be patient. After a month, she could see the benefit: she had started to develop real confidence.',translation:'Раньше Ева занималась часами, а потом бросала учёбу на недели. Она решила обдумать другой подход. Вместо долгих занятий она каждый день прилагала небольшое усилие. Бесплатные уроки были доступны онлайн, а надёжный друг помогал ей практиковаться. Сложность была в том, чтобы сохранять терпение. Через месяц она увидела пользу: у неё начала развиваться настоящая уверенность.',words:['consider','approach','effort','available','reliable','challenge','benefit','develop'],q:'What helped Eva make progress?',answers:['A small effort every day','One very long lesson','Giving up for weeks'],answer:'A small effort every day'}
];
export const sentences:Record<string,string[]>={A1:['I read a book every day','My friend is happy','We learn English at home'],A2:['We enjoy learning together','I want to improve my English','Our journey starts today'],B1:['This is an opportunity to learn','My friends support me','I feel confident when I speak'],B2:['We need a different approach','Progress takes time and effort','This course is available online']};
